### ISSUE TITLE
Amp Validation Issue

### ISSUE THREAD

**Issue by clintfisher** [croutonn/tailwindcss-pseudo-elements#196]
![Screen Shot 2021-05-26 at 7 16 36 AM](https://user-images.githubusercontent.com/1458122/119689897-182edf80-bdfe-11eb-91f7-54e23fb33faf.png)

If the attribute name could be updated to the standard [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) format, the amp validation passes `data-tw-content-before`

Is that something I can change via the `contentUtilities` options?

```
type: boolean | { "prefix": string }
default: { "prefix": "tw-content" }
```

// UPDATE

```
    require('tailwindcss-pseudo-elements')({
      contentUtilities: {
        'prefix': 'data-tw-content'
      }
    }),
```

Works a charm, sorry for filing this issue before seeing this option.

**Comment by croutonn** [comment]
@clintfisher Thanks for the report!

I have added a note to the Readme.
As the problem seems to be solved, I will close the issue.
