### ISSUE TITLE
Combine multiple pseudo classes

### ISSUE THREAD

**Issue by larrifax** [croutonn/tailwindcss-pseudo-elements#45]
Thanks for this plugin! Being able to combine pseudo elements and pseudo classes is really helpful.

However, it is sometimes practical to also be able to combine multiple pseudo classes (possibly also including pseudo elements), e.g. `:checked:hover`.

Would it be possible to extend this plugin so that it also supports "chaining" multiple pseudo classes?

**Comment by croutonn** [comment]
Hi, @larrifax. Thanks for the nice suggestion!

I will consider the implementation.
If all combinations are automatically registered, the build performance will deteriorate, so I think that any combination will be registered in the plugin options.
