### ISSUE TITLE
Cannot "extend" variants when using pseudo-element plugin

### ISSUE THREAD

**Issue by uncvrd** [croutonn/tailwindcss-pseudo-elements#47]
Hi - thanks for this plugin! I've run in to a small issue and I'm not sure if it's intentional but I cannot seem to `extend` my variants to use `after` when using this plugin. For example, when I do the following:

```
  variants: {
    extend: {
      backgroundColor: ['after'],
      position: ['after'],
      inset: ['after']
    }
  }
```

This will NOT generate the pseudo elements since I am extending, however, when I do: 

```
  variants: {
    backgroundColor: ['responsive', 'after'],
    inset: ['responsive', 'after'],
    position: ['responsive', 'after'],
  },
```

It creates the `after` element. While not a dealbreaker it is a little inconvenient having to type out all the other alternatives for `variants`. But I thought I'd bring this up if this isn't behaving as expected.

```
"tailwindcss": "^1.9.5",
"tailwindcss-pseudo-elements": "^1.5.0"
```

**Comment by croutonn** [comment]
Hi, @uncvrd. Thanks for the report!

The `extend` variants seem to work from **tailwindcss v2.0.0**.
I upgraded tailwindcss in devDependencies and now the tests pass😉

**Comment by uncvrd** [comment]
@croutonn oh excellent, I suppose I'll give that a shot. Thanks :)
