### ISSUE TITLE
Upgrading to v1?

### ISSUE THREAD

**Issue by brentrobbins** [croutonn/tailwindcss-pseudo-elements#7]
Are there any plans to upgrade this to work with V1? I just tried this with your configuration and it doesn't work.

**Comment by danimalweb** [comment]
I'd like to see this also!

**Comment by oscar-dotdev** [comment]
+1

**Comment by george-dotdev** [comment]
+1

**Comment by croutonn** [comment]
Fixed to work with the latest version while maintaining compatibility with v0.74!
