### ISSUE TITLE
Generate the class for `empty-content` by default

### ISSUE THREAD

**Issue by nayaabkhan** [croutonn/tailwindcss-pseudo-elements#96]
The instructions on the README show this class could be added using the following plugin:

```js
plugin(function ({ addUtilities }) {
  addUtilities(
    {
      '.empty-content': {
        content: "''",
      },
    },
    ['before']
  )
}),
```
 
I think this class is necessary in many cases. Can't this be generated as default by this plugin?

**Comment by croutonn** [comment]
I would like to implement it in the next major version :)
